### ISSUE TITLE
Qed tutorial as a man page

### ISSUE THREAD

**Issue by aksr** [phonologus/QED#10]
I saw you removed installing `qed-tutorial.html` to man pages.  It think it's a good idea to have `qed-tutorial` as a man page (since `qed` is a bit complex), but it should be first converted to `man` page (I used `go-md2man`).
It works fine—just changing `.html` to `.1` in the `Makefile` after generating it.

What do you think?

**Comment by phonologus** [comment]
I agree that having the tutorial in manpage format is a good idea.

I am currently rewriting the tutorial in `asciidoc` using the `asciidoc` manpage conventions, and from that it will be possible to generate the tutorial in many useful formats, including `html` and `manpage`.

I will definitiely also be including a generated `qed-tutorial` manpage, and including it in the `Makefile` `install` target (but it will go into section `7`, which is where miscellaneous documentation should go).

I'm hoping to have this finished sometime later this week. When done, I'll push the changes to close this Issue.

Thanks for the feedback. It's really helpful to know what people find useful.

**Comment by phonologus** [comment]
I'm about to push a significant rewrite, now in `asciidoc`, which will close this issue.

The (new) manpage version is installed by default with `make install`.

The (new) `html` version is very pretty, and quite readable. For now it stays in the source `doc` subdir.

This was a lot of manual work (pun intended!), so there are bound to be typos, formatting errors, and the like. Please do open new issues when you find any that bug you.
