### ISSUE TITLE
clang warnings

### ISSUE THREAD

**Issue by leahneukirchen** [phonologus/QED#4]
I checked the clang warnings, and I think some are correct:

```
pattern.c:230:16: warning: | has lower precedence than >=; >= will be evaluated first [-Wparentheses]
                if(dflag && c|' '>='a' && c|' '<='z'){
                             ^~~~~~~~~
```

**Comment by phonologus** [comment]
Good catch. I haven't changed that line at all from the original, and I would normally defer to Pike & al., but you're right, it looks like it needs the parens.

The same idiom comes up in line 204, with the parens, so I think it does need fixing.

I've just done a fix, and will push now,
