### ISSUE TITLE
File permissions

### ISSUE THREAD

**Issue by aksr** [phonologus/QED#8]
Almost all files have `755` permissions.  If you agree, they should be changed to `644` (except directories).

**Comment by phonologus** [comment]
Thanks for that.

I have fixed all the permissions. I have been experimenting with both macOS
and the fossil source-code manager, and somewhere along the way something
must have nuked the permissions!

Good spot, thank you.

I've pushed the fix, and closed issue #8.

S.

--
Sean Jensen
